#!/bin/bash
if [ $# != 3 ]
then
echo "Illegal number of arguments. Expected 3" 
exit 1
fi

max=$(echo "if ($1 > $2) { $1 } else { $2 } " | bc -l)
max=$(echo "if ($3 > $max) { $3 } else { $max } " | bc -l)
echo $max
