#!/bin/bash

if [[ "$#" -ne 1 ]]
then
echo Illegal number of arguments. Expected 1 - File name
exit 1
fi

if [[ ! -e "$1" ]]
then
  echo File $1 not found
  exit 1
fi

trash=~/.trash
if [[ ! -d "$trash" ]]
then
  echo Creating "$trash"
  mkdir $trash
fi

num=1
name=$1$num
    
while true 
do
  if [[ ! -e "$trash/$name" ]]
  then
    break
  else 
    num=$(($num + 1))
    name=$1$num
  fi
done

echo File name in trash is $name

ln $1 "$trash/$1$num"
rm $1

log=~/.trash.log
if [[ ! -e "$log" ]]
then
  echo Creating "$log"
  touch $log
fi

echo $PWD/$1 $trash/$1$num >> $log
