#!/bin/bash

if [[ "$#" -ne 1 ]]
then
echo Illegal number of arguments. Expected 1 - File name
exit 1
fi

trash=~/.trash
log=~/.trash.log

while read line
do
  full_name=$(echo $line | awk '{print $1}')
  name=$(basename $full_name)
  in_trash=$(echo $line | awk '{print $2}')

  if [[ "$1" != "$name" || ! -e "$in_trash" ]]
  then
    continue
  fi
  
  echo Found $in_trash. Restore it? "(y/n)"
  read act < /dev/tty

  if [[ "$act" == "y" ]]
  then
    dir=$(dirname $full_name)

    if [[ ! -d "$dir" ]]
    then
      dir=~
    fi

    echo Trying restore file to $dir  ...

    new="$dir/$1"

    while true 
    do
      if [[ -e "$new" ]]
      then
        echo File $new exists. write new file name
        read new_name < /dev/tty
        new="$dir/$new_name"
      else 
        break  
      fi
    done

    ln $in_trash $new
    rm $in_trash

    echo File $new restored
  fi
done < $log

 

