#!/bin/bash

source=~/source
if [[ ! -d "$source" ]]
then
  echo Create "$source" with some files
  exit 1
fi

report=~/backup-report
if [[ ! -e "$report" ]]
then
  echo Creating "$report"
  touch $report
fi

dt=$(date +%Y-%m-%d)
lst_dt=$(ls ~ | grep -E "Backup-[0-9]{4}-[0-9]{2}-[0-9]{2}" | sort -n | tail -1 |
awk '{sub(/Backup-/,"");print $0}') 

if [[ ! -z "$lst_dt" ]]
then
  dts=$(date -d $dt +%s)
  lst_dts=$(date -d $lst_dt +%s )
  dt_diff=$((($dts - $lst_dts) / 60 / 60 / 24)) 
fi

if [[ -z "$lst_dt" || "$dt_diff" -gt 7 ]]
then
  echo Creating "Backup-$dt" >> $report
  mkdir ~/Backup-$dt
  ls $source >> $report
  cp $source/* ~/Backup-$dt
else
  echo Updating "Backup-$lst_dt" at $dt  >> $report
	
  for src_f in $(ls $source) 
  do
    bckp_f=~/Backup-$lst_dt/$src_f
    if [[ -f "$bckp_f" ]]
    then
      size_bckp_f=$(stat $bckp_f -c%s)
      size_src_f=$(stat $source/$src_f -c%s)
  
      if [[ "$size_bckp_f" -ne "$size_src_f" ]];
      then
      	touch $bckp_f"."$dt
        cp $bckp_f $bckp_f"."$dt
	cp $source/$src_f $bckp_f
	echo $src_f $src_f"."$dt >> $report
      fi	
    else 
      cp $source/$src_f ~/Backup-$dt
      echo $src_f >> $report
    fi
  done
fi
