#!/bin/bash

file="art.txt"
new_file="avr.txt"

if [[ ! -e "$file" ]]
then
echo "file from task 4 is not exist"  
exit 1
fi

bash ../lab1/make_file "$new_file"

cur_ppid=0
cnt=0
sum=0

while read line 
do

ppid=$(echo $line | grep -E -o "Parent_ProcessID=[0-9]+" | grep -E -o "[0-9]+")
art=$(echo $line | grep -E -o "Average_Running_Time=[0-9.]+" | grep -E -o "[0-9.]+")

if [ "$ppid" -ne "$cur_ppid" ]
then 
avr=$(echo "$sum/$cnt" | bc -l | sed -e 's/^\./0./')
echo "Average_Running_Children_of_ParentID="$cur_ppid" is "$avr >> "$new_file"
sum=0
cnt=0
cur_ppid=$ppid
fi

sum=$(echo "$sum+$art" | bc -l | sed -e 's/^\./0./')
let cnt+=1
echo $line >> "$new_file"


done < $file

echo "Average_Running_Children_of_ParentID="$cur_ppid" is "$avr >> "$new_file"
