#!/bin/bash

max=0

for pid in $(ls /proc | grep "[0-9]\+")
do
if [[ -e /proc/$pid/status ]]
then

rss=$(cat /proc/$pid/status | grep -E "VmRSS:" | grep -E -o "[0-9]+")
	
if [[ "$rss" != "" ]]
then
max=$(echo "if ($max < $rss) { $rss } else { $max } " | bc -l)
fi

fi
done

echo $max

