#!/bin/bash

max=0

for pid in $(ls /proc | grep -o "[0-9]\+")
do
 
  rss=$(cat /proc/$pid/status 2> /dev/null | grep -E "VmRSS:" | grep -o "[0-9]\+")
  if [[ "$rss" != "" ]]
  then
      max=$(echo "if ($max < $rss) { $rss } else { $max } " | bc -l)
  fi
done

echo $max

